  export const capitals: { [key: string]: string } = {
    Israel: "Jerusalem",
    France: "Paris",
    "United Kingdom": "London",
    "United States": "Washington, D.C.",
    Canada: "Ottawa",
    Germany: "Berlin",
    Italy: "Rome",
    Spain: "Madrid",
    Portugal: "Lisbon",
    Netherlands: "Amsterdam",
    Belgium: "Brussels",
    Switzerland: "Bern",
    Austria: "Vienna",
    Greece: "Athens",
    Turkey: "Ankara",
    Egypt: "Cairo",
    "South Africa": "Pretoria",
    Russia: "Moscow",
    China: "Beijing",
    Japan: "Tokyo",
    "South Korea": "Seoul",
    India: "New Delhi",
    Australia: "Canberra",
    Brazil: "Brasília",
    Argentina: "Buenos Aires",
    Mexico: "Mexico City",
    Sweden: "Stockholm",
    Norway: "Oslo",
    Finland: "Helsinki",
    Denmark: "Copenhagen",
  };